language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      os: linux
python:
  - "3.7"
before_install:
  -   sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -n base -c defaults conda;
      conda config --append channels conda-forge;
      conda info -a;
      echo $(python --version);
install:
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pandas pytest pytest-cov coveralls;
    source activate test-environment;
    pip install -e .;
script:
  -   pwd;
      ls;
      pytest --cov=bw_processing;
      coveralls;
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
        conda install conda-build anaconda-client;
        bash ci/conda_upload.sh;
      fi
