jobs:
- job:
  displayName: ubuntu-18.04-38
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name bw
    displayName: Create Anaconda environment

  - bash: |
      source activate bw
      conda install --yes --quiet -c defaults -c conda-forge --name bw python=$PYTHON_VERSION numpy pytest pytest-azurepipelines pytest-cov
    displayName: Install Anaconda packages

  - bash: |
      source activate bw
      ls
      pwd
      pip install -e .
      pytest --cov=bw_processing
    displayName: pytest

- job:
  displayName: macOS-10.14-38
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name bw
    displayName: Create Anaconda environment

  - bash: |
      source activate bw
      conda install --yes --quiet -c defaults -c conda-forge --name bw python=$PYTHON_VERSION numpy pytest pytest-azurepipelines pytest-cov
    displayName: Install Anaconda packages

  - bash: |
      source activate bw
      pytest --cov=bw_processing
    displayName: pytest

- job:
  displayName: vs2017-win2016-38
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name bw
    displayName: Create Anaconda environment

  - script: |
      call activate bw
      conda install --yes --quiet -c defaults -c conda-forge --name bw python=%PYTHON_VERSION% numpy pytest pytest-azurepipelines pytest-cov
    displayName: Install Anaconda packages

  - script: |
      call activate bw
      pytest --cov=bw_processing
    displayName: pytest
