pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- job:
  displayName: ubuntu-20.04-conda
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  timeoutInMinutes: 8
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name bw
    displayName: Create Anaconda environment

  - bash: |
      source activate bw
      conda install --yes --quiet -c defaults -c conda-forge --name bw python=$PYTHON_VERSION numpy fs pandas pytest pytest-azurepipelines">=1.0"
    displayName: Install Anaconda packages

  - bash: |
      source activate bw
      pytest --color=yes -v
    displayName: pytest

- job:
  displayName: ubuntu-20.04-pip
  pool:
    vmImage: 'ubuntu-20.04'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  timeoutInMinutes: 8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      python --version
      pip --version
      pip install numpy fs pandas pytest pytest-cov pytest-azurepipelines
      echo "which pytest"
      which pytest
      echo "pytest version"
      pytest --version
    displayName: Install packages

  - bash: |
      pytest --color=yes -v --cov-report html --cov=bw_processing
    displayName: pytest

- job:
  displayName: macOS-1015-38-conda
  pool:
    vmImage: 'macOS-1015'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  timeoutInMinutes: 8
  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: conda create --yes --quiet --name bw
    displayName: Create Anaconda environment

  - bash: |
      source activate bw
      conda install --yes --quiet -c defaults -c conda-forge --name bw python=$PYTHON_VERSION numpy fs pandas pytest pytest-azurepipelines">=1.0"
    displayName: Install Anaconda packages

  - bash: |
      source activate bw
      pytest --color=yes -v
    displayName: pytest

- job:
  displayName: macOS-1015-pip
  pool:
    vmImage: 'macOS-1015'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  timeoutInMinutes: 8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      python --version
      pip3 install numpy fs pandas pytest pytest-cov pytest-azurepipelines
    displayName: Install packages

  - bash: |
      pytest --color=yes -v --cov-report xml --cov=bw_processing
    displayName: pytest

- job:
  displayName: macOS-11-pip
  pool:
    vmImage: 'macOS-11'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  timeoutInMinutes: 8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: |
      python --version
      pip3 install numpy fs pandas pytest pytest-cov pytest-azurepipelines
    displayName: Install packages

  - bash: |
      pytest --color=yes -v --cov-report xml --cov=bw_processing
    displayName: pytest

- job:
  displayName: windows-2019-conda
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  timeoutInMinutes: 8
  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name bw
    displayName: Create Anaconda environment

  - script: |
      call activate bw
      conda install --yes --quiet -c defaults -c conda-forge --name bw python=%PYTHON_VERSION% numpy fs pandas pytest pytest-azurepipelines">=1.0"
    displayName: Install Anaconda packages

  - script: |
      call activate bw
      pytest --color=yes -v
    displayName: pytest

- job:
  displayName: windows-2019-pip
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  timeoutInMinutes: 8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      python --version
      pip install numpy fs pandas pytest pytest-cov pytest-azurepipelines
    displayName: Install packages

  - script: |
      pytest --color=yes -v --cov-report xml --cov=bw_processing
    displayName: pytest

- job:
  displayName: windows-2022-conda
  pool:
    vmImage: 'windows-2022'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'

  timeoutInMinutes: 8
  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name bw
    displayName: Create Anaconda environment

  - script: |
      call activate bw
      conda install --yes --quiet -c defaults -c conda-forge --name bw python=%PYTHON_VERSION% numpy fs pandas pytest pytest-azurepipelines">=1.0"
    displayName: Install Anaconda packages

  - script: |
      call activate bw
      pytest --color=yes -v
    displayName: pytest

- job:
  displayName: windows-2022-pip
  pool:
    vmImage: 'windows-2022'
  strategy:
    matrix:
      Python310:
        python.version: '3.10'
      Python39:
        python.version: '3.9'
      Python38:
        python.version: '3.8'
      Python37:
        python.version: '3.7'

  timeoutInMinutes: 8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      python --version
      pip install numpy fs pandas pytest pytest-cov pytest-azurepipelines
    displayName: Install packages

  - script: |
      pytest --color=yes -v --cov-report xml --cov=bw_processing
    displayName: pytest
